# Generated by Django 3.2 on 2021-05-06 05:30

from django.db import migrations, models
import network_API.models


class Migration(migrations.Migration):

    dependencies = [
        ('network_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='advisor',
            name='photo',
            field=models.ImageField(default='', upload_to=network_API.models.Advisor.nameFile),
        ),
    ]
