# Generated by Django 3.2 on 2021-05-06 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_API', '0002_auto_20210506_1100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
